image: maven:3.6.1-jdk-8

cache:
  paths:
    - .m2/repository/
    - target/

deploy:
  stage: deploy
  before_script:
   - apt-get update -y && apt-get install lftp -y
  script:
    - echo "testando..."
    - mvn clean install
    - lftp -e "open ftp://184.107.54.145; set ssl:verify-certificate no;  user $FTP_USERNAME $FTP_PASSWORD; put -O appservers/wildfly-11.0.0.Final/standalone/deployments/ /builds/wallacerodrigon/financas-api/target/financas-api.war; bye"
  allow_failure: false     
  only:
    - develop
